stages:
    - test
    - deploy

cache:
  paths: 
    - wheelhouse/

.toxjob: &toxjob
    stage: test
    before_script:
      - pip install --upgrade pip setuptools setuptools-scm
      - pip install tox pytest-cov
    script:
      - tox

.test27:
  <<: *toxjob
  image: python:2.7
  variables:
    TOXENV: py27

test36:
    <<: *toxjob
    image: python:3.6-alpine
    before_script:
      - apk add --no-cache git gcc musl-dev
      - pip install --upgrade pip setuptools setuptools-scm
      - pip install tox pytest-cov
      - python -c 'import platform; print(platform.libc_ver());'
    variables:
      TOXENV: py36

test361:
    <<: *toxjob
    image: python:3.6.1
    variables:
      TOXENV: py36

.test37:
    <<: *toxjob
    image: python:3.7
    variables:
      TOXENV: py37

.deploy_template: &mydeploy
  stage: deploy
  image: quay.io/pypa/manylinux2010_x86_64
  only:
    - tags
  script:
    - /opt/python/${PYBIN}/bin/pip wheel . -w wheelhouse/
    - auditwheel repair wheelhouse/*.whl --plat manylinux2010_x86_64
  after_script:
    - ls -lh wheelhouse/

deploy27:
  <<: *mydeploy
  variables:
    PYBIN: cp27-cp27mu

deploy35:
  <<: *mydeploy
  variables:
    PYBIN: cp35-cp35m

deploy36:
  <<: *mydeploy
  variables:
    PYBIN: cp36-cp36m

deploy37:
  <<: *mydeploy
  variables:
    PYBIN: cp37-cp37m
