stages:
    - test

.toxjob: &toxjob
    stage: test
    before_script:
      - pip install tox pytest-cov
    script:
      - tox
    after_script:
      - ls -lh .tox/distshare

test36:
    <<: *toxjob
    image: python:3.6
    variables:
      TOXENV: py36

test37:
    <<: *toxjob
    image: python:3.7
    variables:
      TOXENV: py37

