stages:
    - test
    - deploy

cache:
  paths: 
    - /io/wheelhouse/

.toxjob: &toxjob
    stage: test
    before_script:
      - pip install tox pytest-cov
    script:
      - tox

test36:
    <<: *toxjob
    image: python:3.6
    variables:
      TOXENV: py36

test37:
    <<: *toxjob
    image: python:3.7
    variables:
      TOXENV: py37

.deploy_template: &mydeploy
  stage: deploy
  image: quay.io/pypa/manylinux2010_x86_64
  script:
    - ${PYBIN}/pip wheel . -w wheelhouse/
    - auditwheel repair wheelhouse/*.whl --plat manylinux2010_x86_64 -w /io/wheelhouse
  after_script:
    - ls -lh /io/wheelhouse/

deploy36:
  <<: *mydeploy
  variables:
    PYBIN: /opt/python/cp36-cp36mu
