name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        # we need fetch-depth 0 so setuptools_scm can resolve tags

    - uses: actions/setup-python@v2
      name: Install Python
      with:
        python-version: '3.7'

    - name: Build source distribution with Ubuntu
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        python -m pip install --upgrade pip
        pip install build
        python -m build --sdist --outdir dist .

    - name: Install cibuildwheel
      run: |
        python -m pip install cibuildwheel==1.6.4

    - name: Build wheel
      run: |
        python -m cibuildwheel --output-dir dist
      env:
        # build python 3.7 and 3.8
        CIBW_BUILD: cp37-* cp38-*
        CIBW_SKIP: '*-manylinux_i686 *-win32'
        CIBW_BUILD_VERBOSITY_LINUX: 0
        CIBW_BUILD_VERBOSITY_MACOS: 0
        CIBW_BUILD_VERBOSITY_WINDOWS: 0
        # CIBW_BEFORE_ALL_LINUX: >
        CIBW_BEFORE_BUILD_LINUX: >
          python -m pip install --upgrade pip
        CIBW_BEFORE_BUILD_MACOS: >
          python -m pip install --upgrade pip
        CIBW_ENVIRONMENT_MACOS: MACOSX_DEPLOYMENT_TARGET=10.14
        CIBW_BEFORE_BUILD_WINDOWS: >
          python -m pip install --upgrade pip
        CIBW_TEST_REQUIRES: pytest pytest-cov
        # CIBW_BEFORE_TEST: ln -s {project}/tests tests
        CIBW_BEFORE_TEST_WINDOWS: ln -s . c:\cbor2
        CIBW_TEST_COMMAND_WINDOWS: "cd cbor2 && ls -al && pwd && pytest tests"
        CIBW_TEST_COMMAND_MACOS: cd {project} && pytest tests
        CIBW_TEST_COMMAND_LINUX: cd {project} && pytest tests


    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: wheels
        path: ./dist
